BoxLayout:
    orientation: "vertical"
    BoxLayout:
        orientation: "vertical"
        Button:
            text: self.text
        Button:
            text: "products"
        Button:
            text: "products"
        Button:
            text: "products"
        Button:
            text: "products"
    BoxLayout:
        size_hint_y: 0.1
        Label:
            text: "MONEY"
        Button:
            text: "reset"